site_name: Machine Learning Interview Handbook
site_description: Machine Learning, Deep Learning interview questions

repo_url: https://github.com/anujonthemove/Machine-Learning-Interview-Handbook
repo_name: anujonthemove/Machine-Learning-Interview-Handbook


theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky

  palette:
    primary: green
  
  font:
    text: Epilogue


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # The BetterEm extension improves the detection of Markup to emphasize text in Markdown using special characters
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: 'index.md'
  - 'Machine Learning': 'machine-learning.md'
  - 'Deep Learning': 
    - 'Feed Forward Neural Networks': 'feed-forward-nns.md'
    - 'Activation Functions': 'activation-functions.md'
    - 'Setting up': 'setting-up.md'
    - 'Loss Functions' : 'loss-functions.md'
    - 'Optimizers': 'optimizers.md'
    - 'Regularization Techniques': 'regularization-techniques.md'
    - 'Model Training': 'model-training.md'
    - 'Model Evaluation': 'model-evaluation.md'
  - Deep Learning - Computer Vision: 'deep-learning-computer-vision.md'
  - Resources: 'resources.md'